'use client';

/* components/shell/mobile-nav.tsx
 *
 * Verbatim port of the legacy <nav class="bottom-bar"> from
 * public/table.html lines 1842-1859 (and identical across pipeline.html,
 * profile.html, settings.html, analytics.html, report.html).
 *
 * Four tabs: Offers / Analytics / Profile / Settings, each with the
 * inline SVG copied from legacy. Active state derived from usePathname()
 * — legacy hardcodes `class="active"` and `aria-current="page"` per page.
 *
 * Note: the Offers tab links to plain /offers, so the view defaults to
 * the table on every width (a ?view=kanban switch in the URL is never
 * forced by the nav). Marked active on all offers surfaces.
 *
 * CSS lives in app/styles/chrome.css (.bottom-bar / .bottom-bar-tab).
 */

import { Briefcase, LineChart, Settings, User } from 'lucide-react';
import type { Route } from 'next';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

interface MobileTab {
  // Route<string> from next/link.d.ts (generated by typedRoutes) — rejects
  // unknown routes at compile time. All four tab hrefs below are static
  // literals matching real App Router routes.
  href: Route;
  label: string;
  dataTab: string;
  activeOn: string[];
  icon: React.ReactElement;
}

const TABS: MobileTab[] = [
  {
    href: '/offers',
    label: 'Offers',
    dataTab: 'offers',
    activeOn: ['/offers', '/report', '/pipeline', '/table'],
    icon: <Briefcase aria-hidden="true" strokeWidth={1.8} />,
  },
  {
    href: '/analytics',
    label: 'Analytics',
    dataTab: 'analytics',
    activeOn: ['/analytics'],
    icon: <LineChart aria-hidden="true" strokeWidth={1.8} />,
  },
  {
    href: '/profile',
    label: 'Profile',
    dataTab: 'profile',
    activeOn: ['/profile'],
    icon: <User aria-hidden="true" strokeWidth={1.8} />,
  },
  {
    href: '/settings',
    label: 'Settings',
    dataTab: 'settings',
    activeOn: ['/settings'],
    icon: <Settings aria-hidden="true" strokeWidth={1.8} />,
  },
];

export function MobileNav() {
  const pathname = usePathname();
  return (
    <nav className="bottom-bar" aria-label="Mobile navigation">
      {TABS.map(tab => {
        const isActive = tab.activeOn.some(p => pathname === p || pathname.startsWith(`${p}/`));
        return (
          <Link
            key={tab.href}
            href={tab.href}
            className={isActive ? 'bottom-bar-tab active' : 'bottom-bar-tab'}
            data-tab={tab.dataTab}
            aria-current={isActive ? 'page' : undefined}
          >
            {tab.icon}
            <span>{tab.label}</span>
          </Link>
        );
      })}
    </nav>
  );
}
