// Loads frontmatter-format markdown report files (YAML frontmatter +
// markdown body) and runs `marked` for HTML. Non-frontmatter files are
// rejected with an explicit error — the legacy structured-report format is
// no longer supported. The public loadReport wraps the implementation with
// a defensive ReportData.safeParse + fallback layer.

import 'server-only';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import yaml from 'js-yaml';
import { Marked } from 'marked';
import { z } from 'zod';
import { escapeHtml } from '../escape-html';
import { ReportData, ReportFrontmatter } from '../schemas/reports';
import { atomicWrite } from './atomic-write';
import { shortSeniority } from './format';
import { readFileOrNull } from './read-or-null';
import { normalizeReportMarkdown } from './report-markdown';
import {
  cityFromLocations,
  coerceWorkMode,
  VALID_SENIORITY,
  VALID_WORK_MODE,
} from './report-schema';

// ── Sanitizing marked instance ────────────────────────────────────────────────
//
// marked v14 passes raw HTML through by default. Reports are rendered via
// __html injection in the React renderer, so a malicious job-board post
// could inject <script> or <img onerror=...> payloads.
//
// We override the `html` renderer token to escape raw HTML text instead of
// emitting it verbatim. No external dependency required.
const markedSafe = new Marked({
  async: false,
  gfm: true,
  renderer: {
    html({ text }: { text: string }): string {
      // Escape raw HTML blocks so they display as literal text rather than
      // being injected into the DOM.
      return escapeHtml(text);
    },
  },
});

// ── Private constants ─────────────────────────────────────────────────────────

/**
 * APPENDED_SECTION_TITLES — the exact H2 titles that are recognised as
 * appended sections generated by sur9e modes (deep, interview-prep).
 * Case-sensitive; partial matches are rejected.
 */
const APPENDED_SECTION_TITLES = ['Company Research', 'Interview Process'];

// ── Public helpers ────────────────────────────────────────────────────────────

/**
 * Extract free-form H2 sections appended after the core report sections.
 * Only exact title matches (case-sensitive) from APPENDED_SECTION_TITLES are
 * returned -- similar-but-wrong headers like "Company Research X" are skipped.
 */
export function extractAppendedSections(
  md: string,
): Array<{ title: string; body: string; rawHtml: string }> {
  const results: Array<{ title: string; body: string; rawHtml: string }> = [];
  const re = /^##\s+(.+)$/gm;
  const matches: Array<{ title: string; start: number; headerEnd: number }> = [];
  let mm: RegExpExecArray | null;
  while ((mm = re.exec(md)) !== null) {
    matches.push({ title: mm[1].trim(), start: mm.index, headerEnd: mm.index + mm[0].length });
  }
  for (let i = 0; i < matches.length; i++) {
    const { title, headerEnd } = matches[i];
    if (!APPENDED_SECTION_TITLES.includes(title)) continue;
    const end = i + 1 < matches.length ? matches[i + 1].start : md.length;
    const body = md.slice(headerEnd, end).trim();
    results.push({ title, body, rawHtml: markedSafe.parse(body) as string });
  }
  return results;
}

// ── Types ─────────────────────────────────────────────────────────────────────

// loadReport may return either a successful ReportData-shaped object
// (markdown/html/fileName/parsed) or an error envelope ({ error, path }) when
// the file is missing / the filename is invalid.
export type LoadReportResult = ReportData | { error: string; path: string | null };

// ── Frontmatter format (new report file shape) ────────────────────────────────

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/;

export function parseFrontmatter(md: string): { frontmatter: ReportFrontmatter; body: string } {
  const m = md.match(FRONTMATTER_RE);
  if (!m) throw new Error('Report markdown is not frontmatter format (no leading --- block)');
  const yamlText = m[1];
  const body = (m[2] ?? '').replace(/^\s*\n/, '');
  let raw: unknown;
  try {
    raw = yaml.load(yamlText);
  } catch (e) {
    throw new Error(`Frontmatter YAML parse failed: ${(e as Error).message}`);
  }
  // Tolerate reports whose generator omitted the schema-required `status` /
  // `state` metadata — LLM-written frontmatter is occasionally incomplete, and
  // a single missing field must NOT make the whole report unopenable (it
  // previously threw → the page fell back to "report not yet generated"). Each
  // is backfilled from the other, defaulting to an evaluated report. The
  // tracker row remains the authoritative status; this only keeps the file
  // parseable so the body still renders.
  if (raw && typeof raw === 'object' && !Array.isArray(raw)) {
    const r = raw as Record<string, unknown>;
    const statusStr = typeof r.status === 'string' ? r.status.toLowerCase() : '';
    if (r.state == null) {
      r.state = statusStr === 'screened' || statusStr === 'discarded' ? 'screened' : 'evaluated';
    }
    if (r.status == null) {
      r.status = r.state === 'screened' ? 'Screened' : 'Evaluated';
    }
  }
  const parsed = ReportFrontmatter.safeParse(raw);
  if (!parsed.success) {
    throw new Error(`Frontmatter schema invalid: ${parsed.error.message}`);
  }
  return { frontmatter: parsed.data, body };
}

export function serializeFrontmatter(frontmatter: ReportFrontmatter, body: string): string {
  const yamlText = yaml.dump(frontmatter, { lineWidth: 120, noRefs: true, sortKeys: false });
  return `---\n${yamlText}---\n\n${body.replace(/^\n+/, '')}`;
}

export function saveReport(opts: {
  filePath: string;
  // Accept the schema's input shape so callers don't have to pre-fill
  // .default() fields (archetype, tldr). They're materialised by parse().
  frontmatter: z.input<typeof ReportFrontmatter>;
  body: string;
}): void {
  const validated = ReportFrontmatter.parse(opts.frontmatter);
  // Every persist passes through here (the editor save via the PATCH route's
  // whole-body write, plus CLI/migration writers), so
  // normalizing the body here kills editor-serializer corruption (Cause B) on
  // every save without each caller having to remember to do it.
  const body = normalizeReportMarkdown(opts.body).markdown;
  const out = serializeFrontmatter(validated, body);
  atomicWrite(opts.filePath, out);
}

export function isFrontmatterFormat(md: string): boolean {
  return /^---\r?\n/.test(md);
}

// Fields the UI is allowed to edit, with their per-field validators.
// Read-only fields (company, role, score, date, url, num, state) are
// intentionally absent — updateReportFrontmatterField throws on them.
const EDITABLE_FRONTMATTER_FIELDS: Record<string, (v: string) => boolean> = {
  archetype: () => true, // validated against the effective list in the action layer
  seniority: v => v === '' || VALID_SENIORITY.includes(v),
  work_mode: v => v === '' || VALID_WORK_MODE.includes(v),
  location: () => true,
  comp: () => true,
  legitimacy: () => true,
};

// Rewrite ONE frontmatter key on a report file, preserving the body and the
// order of every other key. Throws for unknown/read-only fields or values
// that fail the per-field validator.
//
// Body reconstruction: FRONTMATTER_RE group 2 (m[2]) captures everything after
// the closing `---` line verbatim, so we splice it back as-is — no
// trimming, no newline juggling. The yaml.dump output always ends with `\n`,
// so `---\n${yamlText}---\n${m[2]}` round-trips the file exactly.
export function updateReportFrontmatterField(filePath: string, field: string, value: string): void {
  const validator = EDITABLE_FRONTMATTER_FIELDS[field];
  if (!validator) throw new Error(`field not editable: ${field}`);
  if (!validator(value)) throw new Error(`invalid value for ${field}: ${value}`);

  const raw = readFileSync(filePath, 'utf8');
  const m = raw.match(FRONTMATTER_RE);
  if (!m) throw new Error(`no frontmatter in ${filePath}`);
  const fm = (yaml.load(m[1]) ?? {}) as Record<string, unknown>;
  fm[field] = value;
  // m[2] is the exact bytes after the closing `---\n?` — preserve them verbatim.
  const body = m[2];
  const yamlText = yaml.dump(fm, { lineWidth: 120, noRefs: true, sortKeys: false });
  atomicWrite(filePath, `---\n${yamlText}---\n${body}`);
}

/**
 * Resolve the on-disk report path for an offer number (NNN-slug-date.md).
 * Returns null if no report file exists for that num.
 */
export function reportPathForNum(rootPath: string, num: number): string | null {
  const dir = join(rootPath, 'artifacts', 'reports');
  if (!existsSync(dir)) return null;
  const prefix = `${String(num).padStart(3, '0')}-`;
  const file = readdirSync(dir).find(f => f.startsWith(prefix) && f.endsWith('.md'));
  return file ? join(dir, file) : null;
}

/**
 * Surgically remove a single `<!-- sur9e:running … -->` placeholder comment
 * line from the report file that carries it, matched on `num` + `started`
 * (the run's insert-time ISO timestamp, unique per run). Everything else (the
 * frontmatter, the section the job appended out-of-band, and any other
 * placeholder for a different run) is preserved verbatim.
 *
 * This exists because the in-editor running-mode card serializes to that
 * comment, and clearing the card by mutating the editor would re-serialize
 * the editor's STALE doc (it never holds the job's out-of-band append) and
 * clobber the freshly-written section. The card lifecycle therefore clears
 * the comment server-side here, then hard-reloads to re-sync the editor.
 *
 * Returns true when a matching line was found and removed (or was already
 * absent on a file that still carries the run's stamp, treated as a no-op
 * success), false when no file/line matched.
 *
 * NOTE: resolves the reports dir via `process.cwd()` rather than an explicit
 * rootPath (unlike `reportPathForNum`). Pre-existing; left as-is to avoid
 * changing the running-mode action's call signature.
 */
export function clearRunningModePlaceholder(opts: { num: number; startedAt: string }): boolean {
  const dir = join(process.cwd(), 'artifacts', 'reports');
  if (!existsSync(dir)) return false;
  const numNeedle = `num="${opts.num}"`;
  const startedNeedle = `started="${opts.startedAt}"`;
  let files: string[];
  try {
    files = readdirSync(dir).filter(f => f.endsWith('.md'));
  } catch {
    return false;
  }
  for (const f of files) {
    const filePath = join(dir, f);
    const raw = readFileOrNull(filePath);
    if (raw == null) continue;
    // Cheap pre-filter: skip files that can't possibly match before splitting.
    if (
      !raw.includes('sur9e:running') ||
      !raw.includes(numNeedle) ||
      !raw.includes(startedNeedle)
    ) {
      continue;
    }
    const lines = raw.split('\n');
    const kept = lines.filter(line => {
      const t = line.trim();
      return !(
        t.startsWith('<!-- sur9e:running') &&
        t.includes(numNeedle) &&
        t.includes(startedNeedle)
      );
    });
    if (kept.length === lines.length) return true; // matched file, line already gone
    atomicWrite(filePath, kept.join('\n'));
    return true;
  }
  return false;
}

// ── Private implementation ────────────────────────────────────────────────────

function loadReportImpl(
  rootPath: string,
  slugOrPath: string,
  // statusHint is retained on the signature for the public loadReport wrapper's
  // call-through; the legacy parser that consumed it is gone, so it's unused here.
  _statusHint?: string,
): LoadReportResult {
  // Accept either "001-anthropic-2026-04-15.md" or "artifacts/reports/001-anthropic-2026-04-15.md"
  const fileName = slugOrPath.startsWith('artifacts/reports/')
    ? slugOrPath.slice('artifacts/reports/'.length)
    : slugOrPath;

  // Guard against path traversal -- fileName must be a flat filename, no separators or dot-dot.
  // A NUL byte is equally invalid input (readFileSync throws ERR_INVALID_ARG_VALUE, not ENOENT,
  // and the raw Node error leaks the absolute path) so reject it via the same branch.
  if (
    fileName.includes('..') ||
    fileName.includes('/') ||
    fileName.includes('\\') ||
    fileName.includes('\0')
  ) {
    return { error: 'Invalid filename', path: null };
  }

  // Only canonical report files are servable. The listing functions (findByNum,
  // search) both filter on `.md`; mirror that here so editor/migration backups
  // (.bak) and any other sibling artifacts are never served as reports.
  if (!fileName.endsWith('.md')) {
    return { error: 'Invalid filename', path: null };
  }

  const filePath = join(rootPath, 'artifacts', 'reports', fileName);
  const md = readFileOrNull(filePath);
  if (md == null) {
    // Never expose the absolute on-disk path to callers (info disclosure).
    return { error: 'Report not found', path: null };
  }
  const html = markedSafe.parse(md) as string;

  // Frontmatter-format early-return: new report files store YAML frontmatter +
  // markdown body. We short-circuit the legacy section/YAML-block parser and
  // surface `format` + `body` at top level so the wrapper preserves them.
  if (isFrontmatterFormat(md)) {
    try {
      const { frontmatter, body: rawBody } = parseFrontmatter(md);
      // Heal an already-corrupted file (like #19) on display: normalize the
      // body so the renderer shows clean markdown. Display only — this never
      // writes back; the file persists clean only on the user's next save.
      const body = normalizeReportMarkdown(rawBody).markdown;
      // Synthesize the `summary` shape that loadApplicationsWithSummary
      // reads off parsed reports. Legacy reports populated this from a
      // YAML block; frontmatter reports have the same fields at the
      // frontmatter's top level — just project them back into a
      // summary object for the table normalizer.
      const locValue = Array.isArray(frontmatter.locations)
        ? frontmatter.locations.join(', ')
        : (frontmatter.locations ?? '');
      const summary = {
        compRange: frontmatter.comp_range ?? frontmatter.comp ?? null,
        loc: frontmatter.loc_short ?? locValue ?? null,
        archetype: frontmatter.archetype_short ?? frontmatter.archetype ?? null,
        comp_short: frontmatter.comp_short,
        loc_short: frontmatter.loc_short,
        archetype_short: frontmatter.archetype_short,
        seniority_short: frontmatter.seniority_short ?? shortSeniority(frontmatter.seniority),
        work_mode: frontmatter.work_mode ?? coerceWorkMode(frontmatter.remote),
        company_logo: frontmatter.company_logo,
        archetype_full: frontmatter.archetype,
        comp_full: frontmatter.comp,
        locations: Array.isArray(frontmatter.locations) ? frontmatter.locations : [],
        remote: frontmatter.remote ?? '',
        // Canonical fields read by the surfaces for cross-view sync.
        seniority: frontmatter.seniority ?? '',
        location: frontmatter.location ?? cityFromLocations(frontmatter.locations),
        url: frontmatter.url ?? null,
        // True posting date (optional) — surfaces fall back to the row's
        // added/scan `date` when absent.
        posted: frontmatter.posted,
      };
      return {
        markdown: md,
        html,
        fileName,
        parsed: {
          format: 'frontmatter',
          body,
          ...frontmatter,
          compRange: frontmatter.comp_range,
          summary,
        },
        format: 'frontmatter',
        body,
        ...frontmatter,
        summary,
      } as unknown as LoadReportResult;
    } catch (e) {
      console.warn(`loadReport frontmatter parse error for ${fileName}: ${(e as Error).message}`);
      return { error: 'Frontmatter parse failed', path: null };
    }
  }

  // Any non-frontmatter file is a legacy report. That format is no longer
  // supported — reports are frontmatter-only now. Return an explicit error
  // instead of silently rendering an unparseable structure.
  return {
    error:
      'Legacy report format is no longer supported. Re-run evaluation to regenerate this report.',
    path: null,
  };
}

// ── Public loadReport -- defensive parse-or-fallback wrapper ─────────────────

export function loadReport(
  rootPath: string,
  slugOrPath: string,
  statusHint?: string,
): LoadReportResult {
  const raw = loadReportImpl(rootPath, slugOrPath, statusHint);

  if ('error' in raw) {
    return raw as { error: string; path: string | null };
  }

  // Frontmatter-format short-circuit: skip ReportData.safeParse (which would
  // strip top-level `format` + `body`) so the new dual-read consumers see
  // those fields on the wrapper's return value.
  if ((raw as { format?: string }).format === 'frontmatter') {
    return raw as LoadReportResult;
  }

  const result = ReportData.safeParse(raw);
  if (result.success) return result.data;

  // Schema parse failed -- fall back to `{ ...raw, parsed: null }` so the
  // renderer still shows the markdown. Matches the silent-fall-back behavior.
  console.warn(`reports.ts: schema parse failed for ${slugOrPath}: ${result.error.message}`);
  const rawObj = raw as Record<string, unknown>;
  return {
    markdown: String(rawObj.markdown ?? ''),
    html: String(rawObj.html ?? ''),
    fileName: String(rawObj.fileName ?? slugOrPath),
    parsed: null,
  };
}

export type {
  AppendedSection,
  ParsedReport,
  ReportData,
  ScoringEntry,
} from '../schemas/reports';
